@startuml Adapter Patron

class adapter implements clienteInterface{

    - ntsc: NTSC
    - pal: PAL

    + transformNTSCtoPAL()
    + transformPALtoNTSC()
}

PAL -> clienteInterface
class PAL{
    - fps: double
    - lines: int
    - type: String

    + getFps()
    + getLines()
    + getType()
}

NTSC -> clienteInterface
class NTSC{
    - fps: double
    - lines: int
    - type: String

    + getFps()
    + getLines()
    + getType()
}

interface clienteInterface{
    + transformNTSCtoPAL()
    + transformPALtoNTSC()
}

adapter -> adapterMain
class adapterMain{}

@enduml